// Global settings
:ascii-ids:
:encoding: UTF-8
:lang: en
:icons: font
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:stem:

ifdef::env-github[]
:imagesdir: https://raw.githubusercontent.com/poolborges/jxplorer/main/docs/src/main/images/
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:badges:
:doc-dir: https://github.com/poolborges/jxplorer/tree/main/docs
:repo-base-url: https://github.com/poolborges/jxplorer/
endif::[]

[[doc]]
= JXplorer - A Java Ldap Browser 
:author: Copyright (c) KriolOS Team.
:revnumber: 2025-08-26
:revdate: {last-update-label} {docdatetime}
:version-label!:


WARNING: IN DEVELOPMENT (NOT RELEASE YET)

ifdef::badges[]
== Build status

image:https://github.com/poolborges/jxplorer/actions/workflows/ci.yml/badge.svg["Build Status", link="https://github.com/poolborges/jxplorer/actions/workflows/ci.yml"]
image:https://codecov.io/github/poolborges/jxplorer/coverage.svg["Code Coverage", link="https://codecov.io/gh/poolborges/jxplorer"]
image:https://img.shields.io/badge/License-GPLv3-blue.svg["License: GPL v3", link="https://www.gnu.org/licenses/gpl-3.0.en.html"]
image:https://badges.crowdin.net/krpos/localized.svg["Crowdin/Translation Status", link="https://crowdin.com/project/krpos"]

=== Stats

image:https://img.shields.io/github/issues-pr-raw/poolborges/jxplorer["GitHub Pull Requests", link="https://github.com/poolborges/jxplorer/pulls"]
image:https://img.shields.io/badge/team-committers-green["GitHub Committers", link="https://github.com/orgs/kriolos/teams/obiz-core-team/members"]
image:https://img.shields.io/github/contributors/poolborges/jxplorer["GitHub Contributors", link="https://github.com/poolborges/jxplorer/contributors"]
image:https://img.shields.io/github/commit-activity/m/poolborges/jxplorer["GitHub Commit Activity", link="https://github.com/poolborges/jxplorer/commits"]

=== Release and Download

image:https://img.shields.io/github/release-date-pre/poolborges/jxplorer.svg["GitHub pre-release", link="https://github.com/poolborges/jxplorer/releases"]
image:https://img.shields.io/github/release/poolborges/jxplorer.svg["GitHub release", link="https://github.com/poolborges/jxplorer/releases"]
image:https://img.shields.io/github/downloads/poolborges/jxplorer/total["GitHub all releases", link="https://github.com/poolborges/jxplorer/releases"]

endif::[]


== About 

JXplorer - A Java Ldap Browser
Mature LDAP, LDIF and DSML client with i18n support.
Brought to you by: kingbatman, pegacat, quelgar, trudiersvaer 

A free java ldap client with LDIF support, security (inc SSL, SASL & GSSAPI), 
translated into many languages (inc. Chinese), online help, user forms and many other features. 

== More
* https://github.com/pegacat/jxplorer/
* http://pegacat.com/jxplorer/index.html
* http://jxworkbench.com/
* http://jxworkbench.com/JXWorkBench_Support.html
* http://pegacat.com/index.html

== CA Products 
* 'JXWorkBench' LDAP Enterprise administration product. 
* JXplorer LDAP client. 


=== JXPLORER Libraries

* jxworkbench.jar
* testprovider.jar
* help.jar 
* jhall.jar

== Reference 

* https://github.com/pegacat/jxplorer
* https://sourceforge.net/projects/jxplorer
* http://www.jxplorer.org/