
        package com.ca.directory;
        // automatically generated by ant build.xml file.
        //THIS FILE MUST NOT BE ADDED TO svn OR THE L
        import com.ca.directory.generated.Version;

        public class BuildNumber
        {
            public static String value = "JXplorer (" + Version.getFullVersionWithMeta() + ")";
        }
        